version: '5.0'

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset
      analysis/dataset_definition.py 
      --test-data-file analysis/test_dataset_definition.py
      --dummy-tables dummy_tables
      --output output/dataset.arrow
    outputs:
      highly_sensitive:
        dataset: output/dataset.arrow

  check_dataset:
    run: r:v2 analysis/dataset_checks.R
    needs:
      - generate_dataset
    outputs:
      moderately_sensitive:
        skim: output/dataset_skim.txt
        checks: output/dataset_check.csv
        missing: output/dataset_missing.csv
        status: output/dataset_status.csv
        status_issues: output/dataset_status_issues.csv
        status_reps: output/dataset_status_repeats.csv
        dates: output/dataset_date_outliers.csv
        dates_check: output/dataset_date_outliers_check.csv
        indexes: output/dataset_date_indexes.csv
        indexes_check: output/dataset_date_indexes_check.csv
        plots: output/sample_*.png
        demographics: output/meds_by_*.csv
        text_miss: output/missing_quantities.csv
        text_sum: output/quantity_sums_*.csv
        tex_sum_vis: output/quantity_summary_plot.png
        dmd_sum_vis: output/dmd_summary_plot.png

  quantity_checks:
    run: r:v2 analysis/quantity_checks.R
    needs:
      - generate_dataset
    outputs:
      moderately_sensitive:
        quantity_skim: output/quantity_uoms.csv

  generate_measures:
    run: >
        ehrql:v1 generate-measures
        analysis/measures_definition.py
        --dummy-tables dummy_tables
        --output output/measures/:csv
    outputs:
      moderately_sensitive:
        dataset: output/measures/*.csv
