version: '4.0'

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset
      analysis/dataset_definition.py 
      --dummy-tables dummy_tables
      --output output/dataset.arrow
    outputs:
      highly_sensitive:
        dataset: output/dataset.arrow

  check_dataset:
    run: r:v2 analysis/dataset_checks.R
    needs:
      - generate_dataset
    outputs:
      moderately_sensitive:
        checks: output/dataset_check.csv
  
  generate_measures:
    run: >
        ehrql:v1 generate-measures
        analysis/measures_definition.py
        --dummy-tables dummy_tables
        --output output/measures/:csv
    outputs:
      moderately_sensitive:
        dataset: output/measures/*.csv
